name: cd
on:
  push:
    branches:
      - "**"

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.4

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm run test-unit-run

  component-test:
    name: component-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.4

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: Run component tests
        run: pnpm run test-component-run

  e2e-test:
    name: e2e-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.4

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"
      - run: pnpm install

      - name: Cypress run
        uses: cypress-io/github-action@v4
        env:
          NODE_ENV: ci
        with:
          build: pnpm build
          start: pnpm preview
          browser: chrome
  deploy:
    name: deploy
    needs: [unit-test, component-test, e2e-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./
