name: ci
on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.4

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm run test-unit-run

  component-test:
    name: component-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.4

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: Run component tests
        run: pnpm run test-component-run

  e2e-test:
    name: e2e-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.4

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: pnpm build
          start: pnpm preview
          browser: chrome
